import { Flag, MapPin, Box, Sparkles } from 'lucide-react';

export const availableApis = [
  {
    id: 'flags',
    name: 'Flags API',
    description: 'Bandeiras de países em alta resolução, atualizadas e consistentes.',
    type: 'Images',
    icon: Flag,
    basePrice: 0.001,
    priceFactor: 1.2,
    availability: 'Available',
    color: 'from-red-500 to-orange-500',
  },
  {
    id: 'places',
    name: 'Places API',
    description: 'Imagens de pontos turísticos e lugares famosos ao redor do mundo.',
    type: 'Images',
    icon: MapPin,
    basePrice: 0.002,
    priceFactor: 1.8,
    availability: 'Available',
    color: 'from-green-500 to-emerald-500',
  },
  {
    id: 'logos',
    name: 'Logos API',
    description: 'Logos de empresas, marcas e organizações em formato vetorial.',
    type: 'Vectors',
    icon: Box,
    basePrice: 0.0015,
    priceFactor: 1.5,
    availability: 'Available',
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'icons',
    name: 'Icons API',
    description: 'Biblioteca com milhares de ícones para qualquer tipo de interface.',
    type: 'Vectors',
    icon: Sparkles,
    basePrice: 0.0005,
    priceFactor: 1.1,
    availability: 'Available',
    color: 'from-purple-500 to-pink-500',
  },
];
